# Generated by Django 4.0.6 on 2022-10-28 18:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alfabeto',
            fields=[
                ('id_book', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('letra', models.CharField(max_length=1)),
                ('idioma', models.CharField(max_length=100)),
                ('letra_convertida', models.CharField(max_length=1)),
            ],
        ),
    ]
